### ISSUE TITLE
[HELP] 파일 다운로드 API를 통해서 이미지가 뜨는지 확인해주세요

### ISSUE THREAD

**Issue by chiyongs** [SAMMaru5/SAMMaruClient#15]
## ✍ 문의 사항

url 주소로 파일에 접근하는 방법은 정적 리소스 접근 방법이어서 바로 로드가 되지 않는 것 같습니다.
파일 다운로드 API를 통해서 이미지가 뜨는지 확인해주세요

**Comment by Lucas0105** [comment]
파일 다운로드 API이름이 무엇인가요??

**Comment by chiyongs** [comment]
> 

Swagger - 게시글 API - 파일 다운로드 에 있습니다~~

**Comment by Lucas0105** [comment]
> > 파일 다운로드 API이름이 무엇인가요??
> 
> Swagger - 게시글 API - 파일 다운로드 에 있습니다~~

swagger 접근 시 비인가 에러가 발생하여 해당 api를 찾지 못했습니다.

**Comment by chiyongs** [comment]
> > Swagger - 게시글 API - 파일 다운로드 에 있습니다~~
> 
> swagger 접근 시 비인가 에러가 발생하여 해당 api를 찾지 못했습니다.
4.29 이후로 swagger 버전 변경으로 인한 swagger url 변경 알려드립니다.
http://localhost:8080/swagger-ui/index.html/ 로 변경됐습니다~

**Comment by Lucas0105** [comment]
blob으로 처리한 결과 사진을 불러올 수 없었습니다.
![image](https://user-images.githubusercontent.com/63838039/167464675-8a44a548-96f9-40a7-b8ee-0d046feebc9b.png)

코드
```
    const init = await fetch(`/api/boards/117/articles/118/files/a9aa143c-3291-4e43-ba8f-62dbef72c528.PNG`)

    const blob = await init.blob();
    
    console.log(blob);

    let img = document.createElement('img');
    img.style = 'position:fixed;top:550px;left:400px;width:200px;height:200px;';
    document.body.append(img);
    img.src = URL.createObjectURL(blob);

```

**Comment by Lucas0105** [comment]
사용한 api : /api/boards/117/articles/134/files/3cd46587-6fca-4258-b01f-254693b4e6f1.txt

![image](https://user-images.githubusercontent.com/63838039/167677672-9b99743c-a405-49a8-982b-d4fc5500e2b8.png)

사용한 api : /api/boards/117/articles/134/files/

![image](https://user-images.githubusercontent.com/63838039/167677892-c98ab946-f19f-4200-a7da-e4f5885a654b.png)

api file_path 부분이 없는데도 불구하고 위와 같은 2052 size입니다. 이것은 올바른 데이터를 서버에서 받지 못하는 상황이라 예상됩니다.

때문에 해당 파일을 다운로드 받아 확인한 결과 의미 없는 HTML 파일이 전송된 것을 확인하였습니다.
[blobData (2).txt](https://github.com/SAMMaru5/SAMMaruClient/files/8663466/blobData.2.txt)

**Comment by genius-jo** [comment]
해당 API 그대로 브라우저 주소창에 입력하면, 바로 파일 다운로드가 이루어 지는지 확인 해보시겠나요?

**Comment by Lucas0105** [comment]
죄송합니다.  저의 실수였습니다.
문제는 fetch 호출 시 api만 호출 한 것이 이유였습니다. 
api만 호출하면 서버가 아닌 client 를 호출하여 계속 쓸모없는 값을 받아온 것입니다.

결과
사진을 등록하고 docker를 재 실행하지 않아도 사진을 불러올 수 있는 것을 확인하였습니다.

또한 blob 형태로 데이터를 받아오기 때문에 기존에 useFetch에서 json 형식으로 받아오는 방식은 사용할 수 없게 되었습니다.
새로 customizing 한 useFile 을 만들 예정입니다.
